language: go

go:
  - master

notifications:
  email: false
before_script:
  - go get -t ./...
  - go get honnef.co/go/tools/cmd/megacheck                     # static analyzer/linter
script:
  - go test -v ./...
  - go vet ./...                             # go vet is the official Go static analyzer
  - megacheck ./...                          # "go vet on steroids" + linter
  - go test -v ./fileInfo
